# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0


install:
  - composer install

